name: SurvivalPlus
main: com.fattymieo.survival.Survival
author: FattyMieo
version: "2.0.0"
commands:
   reload-survival:
      description: Reload configurations
      usage: /<command>
   recipes:
      description: Unused
      usage: /<command>
   togglechat:
      description: Toggling between Global and Local Chat
      usage: /<command> [global|local]
      aliases: [tc]
   status:
      description: Checking Hunger and Thirst Status
      usage: /<command>
      aliases: [stat, s]