name: SurvivalPlus
main: tk.shanebee.survival.Survival
authors: [FattyMieo, ShaneBee]
version: 3.6.3
api-version: 1.14
softdepend:
   - PlaceholderAPI
commands:
   reload-survival:
      aliases: [survival-reload]
      description: Reload configurations
      usage: /<command>
      permission: survivalplus.reload
   recipes:
      description: Unused
      usage: /<command>
   togglechat:
      description: Toggling between Global and Local Chat
      usage: /<command> [global|local]
      aliases: [tc]
      permission: survivalplus.togglechat
   status:
      description: Checking Hunger and Thirst Status
      usage: /<command>
      aliases: [stat, s]
   snowgen:
      description: Regenerates snow layers for all chunks, or toggles real-time snow formation
      usage: /<command> [on|off]
      permission: survivalplus.snowgen
   giveitem:
      description: Give a SurvivalPlus item to a player
      usage: /<command> <player> <item>
      permission: survivalplus.giveitem
      aliases: [survivalitem, itemgive]