name: SurvivalPlus
main: com.fattymieo.survival.Survival
authors: [FattyMieo, ShaneBee]
version: 3.0.0
api-version: 1.13
commands:
   reload-survival:
      description: Reload configurations
      usage: /<command>
   recipes:
      description: Unused
      usage: /<command>
   togglechat:
      description: Toggling between Global and Local Chat
      usage: /<command> [global|local]
      aliases: [tc]
   status:
      description: Checking Hunger and Thirst Status
      usage: /<command>
      aliases: [stat, s]
   snowgen:
      description: Regenerates snow layers for all chunks, or toggles real-time snow formation
      usage: /<command> [on|off]
   giveitem:
      description: Give a SurvivalPlus item to a player
      usage: /<command> <player> <item>